services:
  group-calendar:
    build:
      context: .
      network: host
    container_name: group-calendar
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./data:/app/data
