services:
  group-calendar-test:
    build:
      context: .
      network: host
    container_name: group-calendar-test
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.test
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search:
      - .
