services:
  group-calendar:
    build:
      context: .
      network: host
    container_name: group-calendar
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
